base_local_planner:
  DWAPlannerROS:

    # --- Velocity Limits ---
    max_vel_x: 0.45
    min_vel_x: 0.1
    max_vel_y: 0.0
    min_vel_y: 0.0

    min_vel_trans: 0.1

    # --- Rotational velocity ---
    max_vel_theta: 2.0
    min_vel_theta: -2.0 

    # --- Accelerations ---
    acc_lim_x: 0.5
    acc_lim_y: 0.0
    acc_lim_theta: 1.5

    # --- Simulation ---
    sim_time: 1.5
    vx_samples: 20
    vtheta_samples: 40

    # --- Cost function tuning (CLAVE) ---
    path_distance_bias: 20.0
    goal_distance_bias: 15.0
    occdist_scale: 0.8

    # --- Goal tolerances ---
    xy_goal_tolerance: 0.2
    yaw_goal_tolerance: 0.2
    latch_xy_goal_tolerance: false

    # Mejora el comportamiento al esquivar
    #forward_point_distance: 0.3
