#This file contains the parameters for the DWA local planner.
DWAPlannerROS:

# Velocity Limits
  max_vel_x: 0.45
  min_vel_x: 0.1
  
  # So the Pioneer is unidireccional, we don't want lateral velocity
  max_vel_y: 0.0
  min_vel_y: 0.0

  # Translational velocity limits (X)
  # It needs to know the minimum velocity to consider a trajectory valid, 
  min_vel_trans: 0.1

  # --- Rotational velocity limits (Theta) ---
  max_vel_theta: 1.0
  min_vel_theta: -1.0 

  # --- Accelerations ---
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 1.5

    # --- Options ---
    # sim_time: 1.7       
    # vx_samples: 10      
    # vtheta_samples: 20  