common:

  footprint: [[0.25, 0.3], [0.25, -0.3], [-0.25, -0.3], [-0.25, 0.3]]

  stvl_layer:
    enabled: true
    voxel_decay: 0.5
    voxel_size: 0.05
    track_unknown_space: true
    max_obstacle_height: 2.5
    mark_threshold: 0
    update_footprint_enabled: true
    publish_voxel_map: true

    observation_sources: velodyne

    velodyne:
      data_type: PointCloud2
      topic: /velodyne_points
      marking: true
      clearing: true
      min_obstacle_height: 0.15
      max_obstacle_height: 2.0
      obstacle_range: 5.0
      raytrace_range: 5.0

  inflation_layer:
    enabled: true
    inflation_radius: 0.4
    cost_scaling_factor: 5.0